# Generated by Django 6.0.1 on 2026-02-18 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0002_rename_product_cartitems_product_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariant'),
        ),
    ]
