# Generated by Django 6.0.1 on 2026-02-19 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0003_alter_cartitems_product_variant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitems',
            unique_together={('cart', 'product_variant')},
        ),
    ]
