# Generated by Django 6.0.1 on 2026-02-28 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_cartitems_unique_together'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
