# Generated by Django 6.0.1 on 2026-03-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_orderitems_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='last_name',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='address2',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
