# Generated by Django 6.0.1 on 2026-03-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_address_shippingaddress_address1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='postal_code',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
