# Generated by Django 6.0.1 on 2026-02-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantimage',
            name='stripe_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
