# Generated by Django 6.0.1 on 2026-01-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='base_image',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='images/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='variantimage',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/products'),
        ),
    ]
