# Generated by Django 6.0.1 on 2026-01-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productvariant_image_product_base_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantimage',
            name='is_display_image',
            field=models.BooleanField(default=False),
        ),
    ]
