# Generated by Django 6.0.1 on 2026-01-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_variantimage_is_display_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
